const noRandom = [
    'a',
    'aids',
    'analsex',
    'anus',
    'b',
    'bitch',
    'brunst',
    'brunstig',
    'c',
    'd',
    'dildo',
    'drittkjerring',
    'e',
    'ejakulasjon',
    'ejakulere',
    'ereksjon',
    'ereksjonssvikt',
    'erotikk',
    'erotisere',
    'erotisk',
    'faen, fanden',
    'faen i helvete',
    'faen meg',
    'fellatio',
    'folkemord',
    'for faen',
    'forhud',
    'fuck',
    'fucke',
    'fucking',
    'fuckings',
    'fy faen',
    'geil',
    'genitalier',
    'gruppesex',
    'gruppevoldtekt',
    'hardcore',
    'hevnporno',
    'hiv',
    'homoerotikk',
    'homoerotisk',
    'homse',
    'homsegetto',
    'hurpe',
    'hva faen',
    'ikke faen',
    'intimmassasje',
    'jukke, jokke',
    'jævla',
    'jævlig',
    'kjønnsakt',
    'kjønnsdel',
    'kjønnsdrift',
    'kjønnshår',
    'kjønnslem',
    'kjønnslig',
    'kjønnsliv',
    'kjønnsorgan',
    'knull',
    'knulle',
    'komme i buksene på',
    'kukk, kuk',
    'kødd',
    'kåt',
    'kåte opp',
    'kåte seg',
    'l',
    'ligg',
    'ludder',
    'lysten',
    'massakre',
    'massakrere',
    'massemord',
    'massemorder',
    'morrabrød',
    'neger',
    'o',
    'omskjære',
    'omskåren, omskåret',
    'onanere',
    'onani',
    'oralsex',
    'orgasme',
    'orgasmisk',
    'orgastisk',
    'p',
    'penis',
    'penishode',
    'penisrot',
    'penisskaft',
    'pervers',
    'perversjon',
    'pervertere',
    'pikk',
    'porno',
    'pornofilm',
    'pornografi',
    'pornografisk',
    'pornostjerne',
    'prostituere',
    'prostituere seg',
    'prostituert',
    'prostitusjon',
    'pule',
    'pupp',
    'runk',
    'runke',
    'rasshøl',
    'ræv',
    'samleie',
    'seksualitet',
    'seksuell',
    'sex',
    'sexdebutere',
    'sexklubb',
    'sexliv',
    'sexy',
    'sigøyner',
    'skrotum',
    'stå',
    'ståpikk',
    'sæd',
    'sædavgang',
    'sæduttømming',
    'testikkel',
    'testikkelpung',
    'tispe',
    'tøs',
    'tøsaktig',
    'tøsete, tøset',
    'tøyte',
    'uomskåren, uomskåret',
    'utbrettjente',
    'utukt',
    'vagina',
    'vellyst',
    'vellysting',
    'voldta',
    'voldtekt',
    'voldtektsforbryter',
    'æ',
    'ø',
    'å'
];
