// Single-letter dictionary headwords — the alphabet's own letter-name
// entries (e.g. "å" glossed as "the letter and sound å") — kept out of the
// word game's and the random-word feature's random picks, since quizzing
// "what does the letter b mean" isn't a useful vocabulary question.
//
// Deliberately separate from noRandom.js: several of these letters (most
// notably "å", the infinitive marker/interjection/"stream") are also
// legitimate, extremely common real words under the same spelling. A story
// hint popover needs those senses, so stories.js must NOT filter against
// this list — only scripts.js/wordGame.js's random-selection paths should.
const noRandomLetters = [
  "A, a",
  "a",
  "B, b",
  "b",
  "C, c",
  "c",
  "D, d",
  "d",
  "E, e",
  "e",
  "F, f",
  "f",
  "G, g",
  "g",
  "H, h",
  "h",
  "I, i",
  "i",
  "J, j",
  "j",
  "K, k",
  "k",
  "L, l",
  "l",
  "M, m",
  "m",
  "N, n",
  "n",
  "O, o",
  "o",
  "P, p",
  "p",
  "Q, q",
  "q",
  "R, r",
  "r",
  "S, s",
  "s",
  "T, t",
  "t",
  "U, u",
  "u",
  "V, v",
  "v",
  "W, w",
  "w",
  "X, x",
  "x",
  "Y, y",
  "y",
  "Z, z",
  "z",
  "Æ, æ",
  "æ",
  "Ø, ø",
  "ø",
  "Å, å",
  "å",
];
