// Vulgar/explicit headwords excluded from anywhere a word could surface
// without the reader deliberately searching for it: the word game's random
// picks, the "random word" filter in scripts.js, and story-text hint
// popovers (see stories.js's resolveStoryWordEntries — a story about
// classroom desks shouldn't pop up "pult"'s vulgar homograph "pule" as a
// hint). Single-letter alphabet entries (the dictionary's letter-name
// definitions, e.g. "å") are a separate concern with different rules per
// context — see noRandomLetters.js instead.
const noRandom = [
  "aids",
  "alfons",
  "alfonseri",
  "analsex",
  "anus",
  "balle",
  "bedriten",
  "beføle",
  "bitch",
  "bli pisset på",
  "blodskam",
  "blotte seg",
  "bordell",
  "brenne på dass",
  "brunst",
  "brunstig",
  "brystvorte",
  "bullshit",
  "bæsj",
  "bæsje",
  "dass",
  "dildo",
  "dong",
  "dra fanden i vold",
  "dra pokker i vold",
  "drite",
  "drite i",
  "drite seg ut",
  "dritt, drit",
  "drittgod, dritgod",
  "drittjobb, dritjobb",
  "drittkjerring",
  "drittkjerring, dritkjerring",
  "drittkul, dritkul",
  "drittlei, dritlei",
  "drittsekk, dritsekk",
  "drittunge, dritunge",
  "drittvær, dritvær",
  "dægern, dægeren",
  "dæven",
  "ejakulasjon",
  "ejakulere",
  "ekshibisjonisme",
  "ekshibisjonist",
  "elsker",
  "elskov",
  "elskovsscene",
  "ereksjon",
  "ereksjonssvikt",
  "erotikk",
  "erotisere",
  "erotisk",
  "faen heller",
  "faen i helvete",
  "faen meg",
  "faen ta deg",
  "faen, fanden",
  "faenskap",
  "fanden og hans oldemor",
  "fandenivoldsk",
  "fanken, fankeren",
  "fellatio",
  "fetisj",
  "fis",
  "fise",
  "fly forbanna",
  "folkemord",
  "for faen",
  "forbannet, forbanna",
  "fordømt",
  "forhud",
  "fryse pikken av seg",
  "fuck",
  "fucke",
  "fucking",
  "fuckings",
  "fy faen",
  "fy søren",
  "fy til helvete",
  "føkk",
  "føkka, føkket",
  "føkke",
  "føkkings",
  "før fanden har fått sko på",
  "få kukk, få kuk",
  "få ræva i gir, sette ræva i gir",
  "geil",
  "genital",
  "genitalier",
  "gi pokker i",
  "gigolo",
  "glidemiddel",
  "gruppesex",
  "gruppevoldtekt",
  "gå i dass",
  "gå til sengs med",
  "hallik",
  "hallikvirksomhet",
  "hardcore",
  "helvete",
  "helvetes",
  "hersens",
  "hevnporno",
  "hiv",
  "homoerotikk",
  "homoerotisk",
  "homse",
  "homsegetto",
  "hoppe i halmen med noen",
  "hor",
  "hore",
  "horehus",
  "horete, horet",
  "hurpe",
  "husmorporno",
  "hva faen",
  "ikke en dritt",
  "ikke faen",
  "impotens",
  "incest, insest",
  "intimmassasje",
  "jukke, jokke",
  "jævel",
  "jævelskap",
  "jævla",
  "jævlig",
  "kikker",
  "kjønnsakt",
  "kjønnsdel",
  "kjønnsdrift",
  "kjønnshår",
  "kjønnslem",
  "kjønnslig",
  "kjønnsliv",
  "kjønnsorgan",
  "knull",
  "knulle",
  "komme i buksene på, være i buksene på",
  "kondom",
  "kukk, kuk",
  "kødd",
  "kåt",
  "kåte opp",
  "kåte seg",
  "lidderlig",
  "ligg",
  "like forbanna",
  "lort",
  "ludder",
  "lysten",
  "løsunge, lausunge",
  "masochisme, masokisme",
  "masochistisk, masokistisk",
  "massakre",
  "massakrere",
  "massemord",
  "massemorder",
  "megge",
  "morrabrød",
  "munnsex",
  "møkk",
  "møkk, møkka",
  "møkkajobb",
  "møkkavær",
  "neger",
  "nekrofili",
  "offentlig hus",
  "omskjære",
  "omskåren, omskåret",
  "onanere",
  "onani",
  "opp som en hjort og ned som en lort",
  "oralsex",
  "orgasme",
  "orgasmisk",
  "orgastisk",
  "orgie",
  "patte",
  "penetrere",
  "penis",
  "penishode",
  "penisrot",
  "penisskaft",
  "pervers",
  "perversjon",
  "pervertere",
  "pikk",
  "piss",
  "pisse",
  "pisse i buksa for å holde varmen",
  "pisse noen oppetter ryggen, sleike noen oppetter ryggen",
  "pokker",
  "pokkers",
  "porno",
  "pornofilm",
  "pornografi",
  "pornografisk",
  "pornostjerne",
  "promp",
  "prompe",
  "prostituere",
  "prostituere seg",
  "prostituert",
  "prostitusjon",
  "pule",
  "pupp",
  "purke",
  "rammende",
  "rass",
  "rasshøl",
  "rasshøl, rasshull",
  "runk",
  "runke",
  "ræv",
  "ræva",
  "sadisme",
  "sadist",
  "sadistisk",
  "samleie",
  "satan",
  "seksualisere",
  "seksualisme",
  "seksualitet",
  "seksualliv",
  "seksualpartner",
  "seksuell",
  "sex",
  "sexdebut",
  "sexdebutere",
  "sexklubb",
  "sexliv",
  "sexolog",
  "sexologi",
  "sexologisk",
  "sexy",
  "sigøyner",
  "skite",
  "skittstorm",
  "skjede",
  "skrotum",
  "slibrig",
  "slibrighet",
  "som bare pokker",
  "som en dass",
  "sperma",
  "spermie",
  "stå",
  "ståpikk",
  "suge kukk, suge kuk",
  "sugge",
  "sæd",
  "sædavgang",
  "sædcelle",
  "sæddonor",
  "sædgiver",
  "sæduttømming",
  "søren",
  "søtten, sytten",
  "ta med vold",
  "tafse",
  "testikkel",
  "testikkelpung",
  "tispe",
  "tøs",
  "tøsaktig",
  "tøsete, tøset",
  "tøyte",
  "uanstendig",
  "uanstendighet",
  "underliv",
  "uomskåren, uomskåret",
  "usedelig",
  "usedelighet",
  "utbrettbilde",
  "utbrettjente",
  "uterlig",
  "utflod",
  "utukt",
  "utuktig",
  "vagina",
  "vellyst",
  "vellystig",
  "vellysting",
  "voldta",
  "voldtekt",
  "voldtektsforbryter",
  "voyeur",
  "voyeurisme",
];
